#!/bin/sh
set -e

# Write container environment variables to .env file
# so the app can read them via python-dotenv (dotenv_values)
cat > /app/.env <<EOF
AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
AZURE_OPENAI_DEPLOYMENT=${AZURE_OPENAI_DEPLOYMENT}
AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
CONVERSATION_MODE=${CONVERSATION_MODE:-autonomous}
AI_RESPONSE_DELAY_SECONDS=${AI_RESPONSE_DELAY_SECONDS:-2}
MAX_AI_RESPONSES_PER_ROUND=${MAX_AI_RESPONSES_PER_ROUND:-5}
MAX_CONTEXT_MESSAGES=${MAX_CONTEXT_MESSAGES:-50}
ENABLE_STREAMING=${ENABLE_STREAMING:-false}
MEMORY_SUMMARIZATION_INTERVAL=${MEMORY_SUMMARIZATION_INTERVAL:-10}
DATABASE_PATH=${DATABASE_PATH:-data/moltbook.db}
PERSONALITIES_FILE=${PERSONALITIES_FILE:-personalities.json}
SESSION_EXPORT_DIR=${SESSION_EXPORT_DIR:-data/sessions}
EOF

exec python main.py
